name: Publish NuGet package

on:
  push:
    branches:
      - main
      - release/*
    paths:
      - 'src/**'
      - '.github/workflows/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore src/UrbanUI.WPF/UrbanUI.WPF.csproj

      - name: Build
        run: dotnet build src\UrbanUI.WPF\UrbanUI.WPF.csproj --configuration Release --no-restore -p:SourceLinkEnabled=true

      - name: Pack
        run: dotnet pack src\UrbanUI.WPF\UrbanUI.WPF.csproj --configuration Release --no-build --output ./nupkg

      - name: Push to NuGet
        run: |
          Get-ChildItem -Path "./nupkg" -Filter *.nupkg | ForEach-Object {
            Write-Host "Pushing $($_.FullName) to NuGet..."
            dotnet nuget push $($_.FullName) `
              --source https://api.nuget.org/v3/index.json `
              --api-key "${{ secrets.NUGET_API_KEY }}" `
              --skip-duplicate
          }
          
      - name: Push to Github Packages
        run: dotnet nuget add source --username UrbanCastles --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/UrbanUI.WPF/index.json"
          
      - name: Push to Github Packages
        run: |
          Get-ChildItem -Path "./nupkg" -Filter *.nupkg | ForEach-Object {
            Write-Host "Pushing $($_.FullName) to NuGet..."
            dotnet nuget push $($_.FullName) `
              --source "github" `
              --api-key "${{ secrets.NUGET_API_KEY }}" `
              --skip-duplicate
          }

        
